#!/usr/bin/env ruby

# Exit cleanly from an early interrupt
Signal.trap("INT") { exit 1 }

require "appd"
require "appd/cli"


Appd.initialize!

if ARGV[0] != "help" && ARGV[0] != "select" && ARGV[0] != "env" && app = ARGV.shift
  if app == "."
    ARGV << "-p"
    ARGV << Dir.pwd
  else
    ARGV << "-a"
    ARGV << app
  end
end

Appd::CLI.start(ARGV, debug: true)
